
package com.jc.cz_index.core.web.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.jc.cz_index.model.Address;
import com.jc.cz_index.model.AddressSyncLog;
import com.jc.cz_index.model.Card;
import com.jc.cz_index.model.CardSyncLog;
import com.jc.cz_index.model.Certificate;
import com.jc.cz_index.model.CertificateSyncLog;
import com.jc.cz_index.model.Contact;
import com.jc.cz_index.model.ContactSyncLog;
import com.jc.cz_index.model.ContactWay;
import com.jc.cz_index.model.ContactWaySyncLog;
import com.jc.cz_index.model.Person;
import com.jc.cz_index.model.PersonSyncLog;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IFemService", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/")
@XmlSeeAlso({
})
public interface IFemService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.jc.cz_index.core.web.webservice.ContactSyncLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncContact", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncContact")
    @ResponseWrapper(localName = "syncContactResponse", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncContactResponse")
    public List<ContactSyncLog> syncContact(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Contact> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.jc.cz_index.core.web.webservice.CardSyncLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncCard", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncCard")
    @ResponseWrapper(localName = "syncCardResponse", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncCardResponse")
    public List<CardSyncLog> syncCard(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Card> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.jc.cz_index.core.web.webservice.PersonSyncLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncPerson", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncPerson")
    @ResponseWrapper(localName = "syncPersonResponse", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncPersonResponse")
    public List<PersonSyncLog> syncPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Person> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.jc.cz_index.core.web.webservice.ContactWaySyncLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncContactWay", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncContactWay")
    @ResponseWrapper(localName = "syncContactWayResponse", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncContactWayResponse")
    public List<ContactWaySyncLog> syncContactWay(
        @WebParam(name = "arg0", targetNamespace = "")
        List<ContactWay> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.jc.cz_index.core.web.webservice.AddressSyncLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncAddress", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncAddress")
    @ResponseWrapper(localName = "syncAddressResponse", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncAddressResponse")
    public List<AddressSyncLog> syncAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Address> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.jc.cz_index.core.web.webservice.CertificateSyncLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncCertificate", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncCertificate")
    @ResponseWrapper(localName = "syncCertificateResponse", targetNamespace = "http://webservice.web.fem.cz_index.jc.com/", className = "com.jc.cz_index.core.web.webservice.SyncCertificateResponse")
    public List<CertificateSyncLog> syncCertificate(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Certificate> arg0);

}
